import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from 'next-auth/react'
import { useState } from 'react'

import { Button, ButtonGroup } from '@chakra-ui/react'
import Header from 'components/Header/Header'
import CardsContainer from 'components/CardsContainer/CardsContainer'
import Hero from 'components/Hero/Hero'
import Footer from 'components/Footer/Footer'
import axios from 'axios'
import { Product } from '../ts/interfaces/db_interfaces'

interface Products {
  products: Product
}

const Home: NextPage<Products> = ({ products }) => {
  const { data: session, status } = useSession()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Hero />
        <CardsContainer title="New Arrivals" products={products} />
        <CardsContainer title="Trending" products={products} />
        <CardsContainer title="On sale" products={products} />
        <CardsContainer title="Recently Viewed" products={products} />
        <Footer />
      </main>
    </div>
  )
}

// getStaticProps
export async function getStaticProps() {
  const products = await axios
    .get('http://localhost:3000/api/products')
    .then((res) => res.data)

  return {
    props: {
      products,
    },
  }
}

export default Home
